const IR_ENUM = {
  EVENT_START: 1,
  EVENT_EXIT: 3,
  EVENT_ITEM_SHOW: 141,
  EVENT_ONLINE: 161,
  EVENT_OFFLINE: 162,
  EVENT_RECEIVE_DATA: 165,
  EVENT_RECEIVE_TEXT: 166,
  EVENT_TAG_CHANGE: 171,
  EVENT_CHANNEL_SET: 178,

  DEVICE_CUSTOM_TCP: 97,

  ALWAYS_CONNECTED: 0,
  CONNECT_WHEN_SENDING: 1,
  DIRECT_AND_SCRIPT: 0,
  SCRIPT_ONLY: 1,
  BACKGROUND_OFF: 0,
  BACKGROUND_ON: 1
};

module.exports = IR_ENUM;
